//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StayUpdated
{
    using System;
    using System.Collections.Generic;
    
    public partial class NyMedlem
    {
        public int Id { get; set; }
        public string Namn { get; set; }
        public string Efternamn { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string PassConfirm { get; set; }
        public string Personnummer { get; set; }
        public string Mobiltelefon { get; set; }
    }
}
